# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "senexcrenshaw/xteve:latest"
  amd64: "senexcrenshaw/xteve:latest"
  armv7: "senexcrenshaw/xteve:latest"
args:
  XTEVE_PORT: 34401
