# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "fyb3roptik/threadfin:latest"
  amd64: "fyb3roptik/threadfin:latest"
  armv7: "fyb3roptik/threadfin:latest"
