# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Threadfin
version: "0.0.1"
slug: threadfin
description: "Threadfin add-on"
url: "https://github.com/bm735/ha-addons/threadfin"
arch:
  - armv7
  - aarch64
  - amd64
environment:
  - THREADFIN_CONF: "/data/conf"
  - THREADFIN_HOME: "/data"
host_network: true
ports:
  - 34401/tcp: 34401
ports_description:
  - 34401/tcp: "Web interface"
webui: "[PROTO:ssl]://[HOST]:[PORT:34401]/web"
map:
  - share: rw
  - config: rw
  - ssl: ro
image: "ghcr.io/bm735/threadfin-{arch}"
