# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Threadfin add-on
version: "0.0.1"
slug: threadfin
description: Threadfin add-on
url: "https://github.com/bm735/ha-addons/threadfin"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Threadfin..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
