# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Threadfin
version: "0.0.1"
slug: threadfin
description: "Threadfin add-on"
url: "https://github.com/bm735/ha-addons/threadfin"
arch:
  - armv7
  - aarch64
  - amd64
host_network: true
environment:
  THREADFIN_CONF: "/data/conf"
  THREADFIN_HOME: "/data"
  XTEVE_PORT: 34401
  XTEVE_CONF: "/data/conf"
  XTEVE_HOME: "/data"
ports_description:
  34401/tcp: "Web interface"
ports:
  34401/tcp: 34401
webui: "[PROTO:ssl]://[HOST]:[PORT:34401]/web"
map:
  - share:rw
  - homeassistant_config:rw
  - ssl:ro
image: "ghcr.io/bm735/threadfin-{arch}"
